name = "Baml"
grammar = "baml"
path_suffixes = ["baml"]
line_comments = ["// ", "/// "]
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = false },
]
